/**
 * Writes assets/js/config.generated.js from environment variables.
 *
 * NODE_ENV=development (default): loads .env.development, then .env (local overrides).
 * NODE_ENV=production: uses only process.env — set PUBLIC_* in CI/host (no dotenv files).
 */
var fs = require("fs");
var path = require("path");

var nodeEnv = process.env.NODE_ENV || "development";
var isProduction = nodeEnv === "production";

function loadDotenv() {
    try {
        var dotenv = require("dotenv");
        var root = path.join(__dirname, "..");
        var devPath = path.join(root, ".env.development");
        if (fs.existsSync(devPath)) {
            dotenv.config({ path: devPath, override: true });
        }
        var localPath = path.join(root, ".env");
        if (fs.existsSync(localPath)) {
            dotenv.config({ path: localPath, override: true });
        }
    } catch (e) {
        /* dotenv missing before npm install */
    }
}

if (!isProduction) {
    loadDotenv();
}

var siteKey;
var earlyAccessApiUrl;

if (isProduction) {
    siteKey = process.env.PUBLIC_TURNSTILE_SITE_KEY;
    earlyAccessApiUrl = process.env.PUBLIC_EARLY_ACCESS_API_URL;
    if (!siteKey || !earlyAccessApiUrl) {
        console.error(
            "Production build requires PUBLIC_TURNSTILE_SITE_KEY and PUBLIC_EARLY_ACCESS_API_URL in the environment."
        );
        process.exit(1);
    }
} else {
    siteKey =
        process.env.PUBLIC_TURNSTILE_SITE_KEY;
    earlyAccessApiUrl =
        process.env.PUBLIC_EARLY_ACCESS_API_URL;
}

var out =
    "/* auto-generated by scripts/inject-config.js - do not edit */\n" +
    "/* NODE_ENV=" +
    nodeEnv +
    " */\n" +
    "(function () {\n" +
    "  window.__CONFIG__ = {\n" +
    "    turnstileSiteKey: " +
    JSON.stringify(siteKey) +
    ",\n" +
    "    earlyAccessApiUrl: " +
    JSON.stringify(earlyAccessApiUrl) +
    "\n" +
    "  };\n" +
    "})();\n";

var outPath = path.join(__dirname, "..", "assets", "js", "config.generated.js");
fs.writeFileSync(outPath, out, "utf8");
console.log("Wrote " + outPath + " (" + nodeEnv + ")");
